name: Github Actions

on: 
  push:
    branches:
      - main
      - develop
      - code-tidyness

jobs:
  test:
    name: Running unit tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1 

    - name: Use Node.js ${{ matrix.node-version }} ðŸ¤˜
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Back ðŸ”§
      run: npm install

    - name: Install Front ðŸ”§
      run: cd client && npm install
    
    